platform :ios, '8.0'
def pods
pod 'MJRefresh', '~> 3.1.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.2'
pod 'MJExtension', '~> 3.0.13'

end
target '521Travel.com_cellCustom' do
  pods
end
